# Generated by Django 4.2.3 on 2024-12-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='login',
            field=models.CharField(default='admin', max_length=100),
        ),
        migrations.AddField(
            model_name='professor',
            name='senha',
            field=models.CharField(default='adminadmin', max_length=100),
        ),
    ]
