# Generated by Django 5.1.4 on 2024-12-17 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_inscricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='vagas',
            field=models.IntegerField(),
        ),
    ]
